### ISSUE TITLE
Copy the executable generating NetCDF diagnostic file and NYSM convinfo table to default path

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#10]
@Hui4ying3LUO2 
Could you please copy /network/rit/lab/josephlab/LIN/GSI/build/bin/nc_diag_cat.x to the default GSI path?

**Comment by Hui4ying3LUO2** [comment]
I will.

**Comment by weiwilliam** [comment]
@Hui4ying3LUO2
Huiying, additional thing.
Please copy /network/rit/home/sw651133/develop/global_convinfo_nysmsfc.txt to GSI path as well.
Thanks.

**Comment by Hui4ying3LUO2** [comment]
cat.x copied. cp: cannot stat
‘/network/rit/home/sw651133/develop/global_convinfo_nysmsfc.txt’:
Permission denied.


On Tue, Apr 5, 2022 at 7:55 PM weiwilliam ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> @Hui4ying3LUO2
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHui4ying3LUO2&data=04%7C01%7C%7C14e3eb84077d42f38be708da175fcc88%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637847997469656712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8eV1PGX0ZeqcRriwRR%2BmvnTN3ZmjWI8jf5It0v5hZYk%3D&reserved=0>
> Huiying, additional thing.
> Please copy /network/rit/home/sw651133/develop/global_convinfo_nysmsfc.txt
> to GSI path as well.
> Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiwilliam%2FWx-AQ_LuLab%2Fissues%2F10%23issuecomment-1089542580&data=04%7C01%7C%7C14e3eb84077d42f38be708da175fcc88%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637847997469656712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kEP43EHuhABIDoxCN5ryYGrXRteT0fp2HiWWxhNQwHY%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPQGWUJJFYAC5RXUPR6AATLVDTHIBANCNFSM5SUHRGXA&data=04%7C01%7C%7C14e3eb84077d42f38be708da175fcc88%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637847997469656712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p1qInL00v72jNjZ7gNXY43fLyzUAH%2B44lCzL077Jj0g%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
*........................................................................................*
*    Huiying Luo * Ph.D.

    Department of Civil and Environmental Engineering

    University of Connecticut

    261 Glenbrook Road

    Storrs, CT 06269-3037
    Phone: 860-617-3285
*........................................................................................*

**Comment by weiwilliam** [comment]
I move it to /network/rit/lab/lulab/sw651133/global_convinfo_nysmsfc.txt
Please give it a try.

**Comment by Hui4ying3LUO2** [comment]
done!

On Wed, Apr 6, 2022 at 12:04 AM weiwilliam ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> I move it to /network/rit/lab/lulab/sw651133/global_convinfo_nysmsfc.txt
> Please give it a try.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiwilliam%2FWx-AQ_LuLab%2Fissues%2F10%23issuecomment-1089780209&data=04%7C01%7C%7C1bd93cf5c0064feb2f0f08da17828874%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637848146645912019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FppG3Tf%2B4uuHGzagFfE2yiIjAbAgt3%2Fqxzegfd1%2FScw%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPQGWUJVECNW23ALBCOXVNDVDUEMLANCNFSM5SUHRGXA&data=04%7C01%7C%7C1bd93cf5c0064feb2f0f08da17828874%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637848146645912019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2hLhKrKe1fv1ghSjxCYO7rQHt05rZjkXtSSCGSd0u6Q%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
*........................................................................................*
*    Huiying Luo * Ph.D.

    Department of Civil and Environmental Engineering

    University of Connecticut

    261 Glenbrook Road

    Storrs, CT 06269-3037
    Phone: 860-617-3285
*........................................................................................*
