### ISSUE TITLE
[bugfix] The loading errors about shared libraries in Wx-AQ v1.0

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#13]
There are share library errors for real.exe, wrf.exe, and megan_bio_emiss.
For real and wrf, the message is "error while loading shared libraries: libhdf5_fortran.so.10"
For megan_bio_emiss, "error while loading shared libraries: libnetcdf.so.11"
I suspect they are due to the setting in env.sh.
By adding the path of HDF5 library into LD_LIBRARY_PATH, @dpgrogan27 can solve the problems in real and wrf.

@Hui4ying3LUO2 and @clin-nick 
Could you please share your environment setting?

**Comment by clin-nick** [comment]
I put my bash_profile in /network/rit/lab/lulab/share_lib/bash_profile_clin

**Comment by weiwilliam** [comment]
Great, thanks, @clin-nick.
I'll give it a try.

**Comment by weiwilliam** [comment]
It works by using LD_LIBRARY_PATH in @clin-nick bash profile.
I'll submit another pull request later.

**Comment by weiwilliam** [comment]
Fixed in PR #21 by including updated LD_LIBRARY_PATH in env.sh
