### ISSUE TITLE
sample namelist.input for no chem run

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#20]
@clin-nick 
I'm trying to run with the wrf-chem executable with chem_opt = 0
But it complains about the error message below

FATAL CALLED FROM FILE:  <stdin>  LINE:     337
ERROR: wet scavenging option requires chem_opt = 8 through 13 or 31 to 36 or 41 to 42 or 109 or 503 or 504 or 601 or 611 to function.

It seems like changes of other namelist variables in chem section are needed when set chem_opt = 0
Do you have a namelist.input that can run meteorology only with wrf-chem executable?
Thanks.

**Comment by clin-nick** [comment]
I add one namelist in /network/rit/lab/lulab/share_lib/namelist.input_chem0.
I usually just comment out all emission input options in &time_control and all options in %chem, except for chem_opt=0.

**Comment by weiwilliam** [comment]
Great, thanks.
I try to run without chemistry because GSI encounters errors with the output from WRFCHEM.
I guess the error is due to chemistry fields.

**Comment by weiwilliam** [comment]
In PR #21, part of &time_control and &chem in namelist.input are determined by chem_opt.
