### ISSUE TITLE
Updated global convinfo for different prepbufr datasets of LISTOS period

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#24]
@Hui4ying3LUO2 
I got the updated global convifo from Hsiao-Chun and modified it for different prepbufr sets.
There are three files, global_convinfo_nysmsfc_lidar_mwr.txt, global_convinfo_nysmsfc_lidar.txt, and global_convinfo_nysmsfc.txt.
Please check them in /network/rit/lab/lulab/sw651133 and copy them to /network/rit/lab/lulab/WRF-GSI/src/GSI.
Thanks.

**Comment by Hui4ying3LUO2** [comment]
Sure.
It seems the last one global_convinfo_nysmsfc.txt has a previous copy under
/network/rit/lab/lulab/WRF-GSI/src/GSI and is slightly different from this
new one. Could you please let me know how should they be arranged? Many
thanks!


On Wed, May 4, 2022 at 3:43 PM weiwilliam ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> @Hui4ying3LUO2
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHui4ying3LUO2&data=05%7C01%7C%7C2d19097fa26d414850c008da2e0649d8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637872901791846999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ezhDBg5f%2FZ1wI9FgbNmqr3w4jQXv0GDRRmW45jVbNg4%3D&reserved=0>
> I got the updated global convifo from Hsiao-Chun and modified it for
> different prepbufr sets.
> There are three files, global_convinfo_nysmsfc_lidar_mwr.txt,
> global_convinfo_nysmsfc_lidar.txt, and global_convinfo_nysmsfc.txt.
> Please check them in /network/rit/lab/lulab/sw651133 and copy them to
> /network/rit/lab/lulab/WRF-GSI/src/GSI.
> Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiwilliam%2FWx-AQ_LuLab%2Fissues%2F24&data=05%7C01%7C%7C2d19097fa26d414850c008da2e0649d8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637872901791846999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y46u%2BjrziZ7%2Bm0voOobLV9weHGG8IoW16A8h6sPHHR0%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPQGWUMQZVC2FLF62YERIH3VILHMBANCNFSM5VC7RXCA&data=05%7C01%7C%7C2d19097fa26d414850c008da2e0649d8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637872901791846999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EOtbEjKJ%2F%2Fk1q6aHM1SAJOQ18ter7pF6g9o3nFAhE4A%3D&reserved=0>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>


-- 
*........................................................................................*
*    Huiying Luo * Ph.D.

    Department of Civil and Environmental Engineering

    University of Connecticut

    261 Glenbrook Road

    Storrs, CT 06269-3037
    Phone: 860-617-3285
*........................................................................................*

**Comment by weiwilliam** [comment]
Please copy the updated one to overwrite the previous copy.

**Comment by Hui4ying3LUO2** [comment]
Done.

On Wed, May 4, 2022 at 5:29 PM weiwilliam ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> Please copy the updated one to overwrite the previous copy.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiwilliam%2FWx-AQ_LuLab%2Fissues%2F24%23issuecomment-1117954940&data=05%7C01%7C%7C64d6157f683442458ce408da2e153526%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637872965854532310%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OblbDLbHzPuuV7TzA6qwQ%2BII2RyolJ3h3Quh2fTNIcQ%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPQGWUODS2V3WRLVUV2HMPTVILT4RANCNFSM5VC7RXCA&data=05%7C01%7C%7C64d6157f683442458ce408da2e153526%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637872965854532310%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ERu5ur%2FI1J9%2BUzUhG6cs86yyOTQT34jtEaXtSxIs9%2FA%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
*........................................................................................*
*    Huiying Luo * Ph.D.

    Department of Civil and Environmental Engineering

    University of Connecticut

    261 Glenbrook Road

    Storrs, CT 06269-3037
    Phone: 860-617-3285
*........................................................................................*

**Comment by weiwilliam** [comment]
Great, thanks. @Hui4ying3LUO2
