### ISSUE TITLE
Chem data feeding (from global forecast)

### ISSUE THREAD

**Issue by clin-nick** [weiwilliam/Wx-AQ_LuLab#26]
WACCM data can be used:  https://www.acom.ucar.edu/waccm/DATA/

Then, the procedure will be the same as retro run using mozbc to update wrfinput and wrfbdy

**Comment by weiwilliam** [comment]
@clin-nick Sounds great! We'll need to decide how to host those data.
Do you think the forecasts of each initial time are valuable to keep?
Or can we grab and keep the data like the path you posted?

**Comment by weiwilliam** [comment]
@clin-nick Which one would you recommend using, 001 or 002?
001 uses FINN, while 002 uses QFED
I guess 001?

**Comment by clin-nick** [comment]
Yes, I think 001. ACOM uses 001 for the chem bc.
I do find ACOM's bash script to run the forecast. As I remember, they download the data from that path (e.g. script: curr_day_file="https://www.acom.ucar.edu/waccm/DATA/f.e21.FWSD.f09_f09_mg17.forecast.001.cam.h3.${curr_day}-00000.nc)
I will check their script to see if they keep the data or not when I can log into cheyenne.

**Comment by Hui4ying3LUO2** [comment]
@weiwilliam Hi Shih-Wei, I think it's better for you to manage and log all input data for consistency. The FINN data pulling sample code is located in the first portion of the following file (data normally available right before midnight (MT I guess), so we will use the previous day for the current day simulation; you can keep the name as is. I will deal with the "previous day" situation when using the data). Let me know when you're done with both FINN and WACCM. Many thanks!

/network/rit/lab/lulab/share_lib/WRF/Prep_EM/FINN/NRT/example_process_finn_emis.bash

**Comment by weiwilliam** [comment]
@Hui4ying3LUO2 Thanks! I'll manually bring some can data for you to test and update the scripts.
Here I list the tasks to be done in this issue:
- [ ] Integrate the WACCM and FINN pulling scripts to prepdata
- [ ] Download some can data for testing
- [ ] Kick-off and monitor the cronjob for WACCM and FINN.
- [ ] Test and update the scripts with can data (by @Hui4ying3LUO2 )

Please feel free to add working tasks and check the box if you can do it on this comment.
If not, just reply below.

**Comment by weiwilliam** [comment]
@Hui4ying3LUO2 the latest 10-day WACCM files are ready at /network/asrc/scratch/lulab/sw651133/nomads/chem/waccm 
And the FINN data will be downloaded to /network/asrc/scratch/lulab/sw651133/nomads/chem/finn
Please give it a try and update the associated paths in scripts.

**Comment by Hui4ying3LUO2** [comment]
Sure. Many thanks!

**Comment by weiwilliam** [comment]
It is merged to master, PR #33.
