### ISSUE TITLE
Update the domain size or the anthropogenic emission file, wrfchemi_*

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#50]
The current single 4-km domain encounters an emission issue that 4-km NEI doesn't cover the area north of ~46N. 
Possible solutions:
1. move the northern boundary south
2. generate wrfchemi with 12-km and 4-km NEI both and bring 12-km NEI for those regions with low emission in 4-km NEI.

**Comment by weiwilliam** [comment]
@clin-nick Chin-An, Sarah mentioned you have a tool to fill the global emissions to the region outside of 4km NEI. We can work on this issue when you come back.

**Comment by clin-nick** [comment]
Sure. 12-km NEI covers up to part of Canada. If the domain is still outside of 12-km NEI, we can use global emission (EDGARv5) and merge that with 12-km and 4-km NEI.

**Comment by weiwilliam** [comment]
@Hui4ying3LUO2 We can try to see if 'ncks' is easier and more efficient. Let me know if you need my explanation on anything.

**Comment by weiwilliam** [comment]
Done.
