### ISSUE TITLE
documentation and release note

### ISSUE THREAD

**Issue by SarahLu-NOAA** [weiwilliam/Wx-AQ_LuLab#53]
I suggest that we sync the release note in wiki and doc in one-drive.   While I like stand-alone Words doc, I feel that we should consolidate all doc (along with code) in one place (github in this case).    Also, we should revisit whether it's time to have release note v1.1

**Comment by weiwilliam** [comment]
Agree, we can have OneDrive as the working directory, and bring them over GitHub using GitHub desktop or terminal (in macOS) when it's ready. I'd suggest a "doc" folder to keep the version notes. In my mind, there will be one doc for one release and we update it when a new release comes.

**Comment by weiwilliam** [comment]
Yes, we can make it available in the repo as well. It means placing the docx file in a "doc" folder under this repository. I thought you are thinking about it.

**Comment by SarahLu-NOAA** [comment]
What I'm asking is whether to make the doc available before it's finalized.
One option is to add 'Draft' or 'Planned'.. in the doc so the viewers know that it's still in progress??

**Comment by weiwilliam** [comment]
Okay, let me put it in another way. We work on documents in OneDrive and publish it when they are ready. The publish will include the release note on Github (website interface) and the version document (what we have on OneDrive now) under version control.

**Comment by SarahLu-NOAA** [comment]
I notice that Table 1 in v1.0 and v1.1 is different (such as vertical layers, domain..etc).   Could Dustin or others please check the documentation before being posted at the wiki. thanks

**Comment by weiwilliam** [comment]
> I notice that Table 1 in v1.0 and v1.1 is different (such as vertical layers, domain..etc). Could Dustin or others please check the documentation before being posted at the wiki. thanks

Yeah, that is correct.
It's ACOM's configuration based on the namelist provided by @clin-nick , which has specific eta values to define vertical layers.
@clin-nick Can you double check this?

**Comment by clin-nick** [comment]
Yes, Wx-AQ v1.1 adapts ACOM's configuration. There are 43 vertical levels with specific eta levels.

**Comment by weiwilliam** [comment]
Done, https://github.com/weiwilliam/Wx-AQ_LuLab/wiki/Release-Notes-Wx-AQ-v1.1.0
