### ISSUE TITLE
Code structure in prepchem.bash

### ISSUE THREAD

**Issue by dpgrogan27** [weiwilliam/Wx-AQ_LuLab#72]
The following call structure needs refinement in prepdata.bash

ORIGINAL: 
if [ -s $exe -a -s $inp ] ; then
    $aprun -np 16 $exe
fi
error=$?
if [ ${error} -ne 0 ]; then
  echo "ERROR: ${myname} crashed Exit status=${error}." >> $logfile
  echo "Unsuccessfuly run of real.exe with chem on." >> $logfile
  exit ${error}
fi

REFINED (suggested):
if [ -s $exe -a -s $inp ] ; then
    $aprun -np 16 $exe
    error=$?
    if [ ${error} -ne 0 ]; then
         echo "ERROR: ${myname} crashed Exit status=${error}." >> $logfile
         echo "Unsuccessful run of real.exe with chem on." >> $logfile
         exit ${error}
    fi
else
    echo "ERROR: ${aprun} ${exe} not called. crashed Exit status=##." >> $logfile
    echo "Unsuccessful run of real.exe with chem on." >> $logfile
         exit ${error}
fi

This will show whether the $aprun is actually called. This structure is used in many instance in prepdata.chem. 
Before going through and changing them, I wanted to confirm with @weiwilliam on this.

**Comment by weiwilliam** [comment]
@dpgrogan27 I would suggest changing the message when either $exe or $inp does not exist.
`echo "ERROR: $exe or $inp does not exist."`
