### ISSUE TITLE
Traffic control during busy times on Kratos

### ISSUE THREAD

**Issue by dpgrogan27** [weiwilliam/Wx-AQ_LuLab#73]
On Feb 28th, server traffic cause a delay in the 0Z run, which resulted in the 06 and 12Z queued at the same time:
   5868848    kratos            WRF_2023022800 dg771199  RUNNING    2:55:46    7:04:14   4 kratos-[02,08,10,12]
   5870256    kratos            WRF_2023022806 dg771199  PENDING       0:00   10:00:00   4 (Resources)
   5871066    kratos            WRF_2023022812 dg771199  PENDING       0:00   10:00:00   4 (Priority)

Eventually, all cases were run, but because the 6Z and 12Z were looking for wrfout's from the previous cycle, the system did not cycle.
Therefore, because this will be an expected problem in the future, perhaps we can use a CHECKPOINT to determine whether firstrun is 0 or 1 using squeue calls.

Current determination of firstrun:
```
    ## First Cycle Check ##
    # Look to see if sdate wrfout (6 hr fcst) is in pdate rundir.
    if [ ! -f $runpath/$pdate/wrf/wrfout_d01_${syr}-${smon}-${sday}_${shr}:00:00 ]; then
       firstrun=1
       echo "WRF-GSI: FIRST CYCLE" >> $logfile
    else
       firstrun=0
       echo "WRF-GSI: NOT FIRST CYCLE" >> $logfile
    fi
```

Future determination of firstrun:
```
    ## First Cycle Check ##
    #CHECKPOINT TO ENSURE PREVIOUS RUN COMPLETED
       JOBSQUEUE="`which squeue` -u ${USER}"
       SQFORMAT="%.10i %.9P %.25j %.8u %.8T %.10M %.10L %.3D %R"
       sqrc=0
       until [ $sqrc -ne 0 ]
       do
             $JOBSQUEUE -o "${SQFORMAT}" | grep "WRF_$pdate"
             sqrc=$?
             sleep 60
      done
    # Look to see if sdate wrfout (6 hr fcst) is in pdate rundir.
    if [ ! -f $runpath/$pdate/wrf/wrfout_d01_${syr}-${smon}-${sday}_${shr}:00:00 ]; then
       firstrun=1
       echo "WRF-GSI: FIRST CYCLE" >> $logfile
    else
       firstrun=0
       echo "WRF-GSI: NOT FIRST CYCLE" >> $logfile
    fi
```

Let me know if you think this will work or more conditions are needed.

**Comment by weiwilliam** [comment]
@dpgrogan27 I feel it's not good for the NRT system. This may result in a huge delay after many cycles. Then the forecasts of this system become meaningless. If the traffic issue keeps happen, it means Kratos is not appropriate to run an operational-like system.

**Comment by dpgrogan27** [comment]
Thanks for your feedback @weiwilliam. I see that this may cause problems by backing up too much. What if we paused only if the previous cycle was "RUNNING" WRF, rather than "PENDING"? This could surely help in some instances and the delay would only be for a short time. Let me know. thanks

**Comment by weiwilliam** [comment]
@dpgrogan27 Yeah, it could work. We can do pausing on "RUNNING" and dicard the "PENDING" cycle to release the resource.
