### ISSUE TITLE
Resource solution

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#80]
@SarahLu-NOAA @dpgrogan27 @clin-nick 
As you know by the email from John, they are planning to have us share the 4 nodes reserved for Dr. Gonzales-Cruz CUERG.
According to Dr. Gonzales-Cruz's reply, he is fine with the solution but his system is going to include chemistry next month.
It means the system will run much longer than 4 hours now (starting at 4:45-5:00 AM every day).
Our system starts the 00z cycle around 09:20 AM.
I suggest we have a meeting with them to seek the best arrangement for both systems (clarify needs from both ends).

A possible schedule in my mind now is (in eastern time),
02:30, Wx-AQ 00z (GDAS prepbufr ready, but it means we need to use WACCM forecasts from the previous day)
07:00, CUERG
20:00, Wx-AQ 06z
22:00, Wx-AQ 12z
00:00, Wx-AQ 18z
The second solution (if CUERG would like to run earlier), we can shift about 2 hours earlier because GFS 36 hours output should be ready before 00:00.
The problem is, we don't know how much performance could it affect.
The changes to our system:

- For 1st schedule: (1) older WACCM for BCs and (2) older fire emission (maybe)
- For 2nd schedule: (1) assimilating GFS prepbufr, (2) older WACCM for BCs, and (3) older fire emissions.

Please let me know if you have any ideas 💡

**Comment by SarahLu-NOAA** [comment]
@weiwilliam 
Thanks for looking into this. Let me check with Jorge on the run time once Chem is on.
