### ISSUE TITLE
WACCM and FINN download

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#86]
@clin-nick @SarahLu-NOAA 
I found that WACCM and FINN fetching failed two days in a row.
Not sure whether their server is down, I can't reach https://www.acom.ucar.edu now.
It may be back tomorrow, if not, Chin-An, can you check it? Thank you!

**Comment by clin-nick** [comment]
I cannot access WACCM and ACOM webpage now either.
Sure. I will check that with Rajesh.
________________________________
From: Shih-Wei Wei ***@***.***>
Sent: Sunday, April 23, 2023 3:00 PM
To: weiwilliam/Wx-AQ_LuLab ***@***.***>
Cc: Lin, Chin-An ***@***.***>; Mention ***@***.***>
Subject: [weiwilliam/Wx-AQ_LuLab] WACCM and FINN download (Issue #86)


@clin-nick<https://github.com/clin-nick> @SarahLu-NOAA<https://github.com/SarahLu-NOAA>
I found that WACCM and FINN fetching failed two days in a row.
Not sure whether their server is down, I can't reach https://www.acom.ucar.edu now.
It may be back tomorrow, if not, Chin-An, can you check it? Thank you!

**Comment by SarahLu-NOAA** [comment]
I can't access DTC website this weekend.
The Mesa lab is closed this weekend, and I'm not sure whether this closure affect these UCAR/NCAR servers.

**Comment by weiwilliam** [comment]
Seems like back to normal now. Close it.
