### ISSUE TITLE
Extending to 54 hours forecasts

### ISSUE THREAD

**Issue by weiwilliam** [weiwilliam/Wx-AQ_LuLab#89]
Given the need for the DEC AQ forecast discussion at 1:30 PM ET, we have to extend the forecast from 36 to 52 (at least) to provide the next-day forecast.
For example, AQ forecast discussion on Apr 26 1:30 PM ET requires the forecast products to cover the whole day of Apr 27 in ET.
It means the period is Apr 27 04Z to Apr 28 04Z.
Apr 28 04Z is the 52 hours forecast for the cycle initiated from Apr 26 00Z.

- [x] Check the wall-time for 54 hours WRF-Chem run
- [x] Adjust the cronjob schedule

**Comment by weiwilliam** [comment]
On the first try with 20230418 00z, it failed at 38 hours forecast.

**Comment by weiwilliam** [comment]
@clin-nick @SarahLu-NOAA 
The traceback log shows it failed at the same line 1768 in module_ftuv_subs.f90 as we shared with Rajesh last week.
![image](https://user-images.githubusercontent.com/10061966/234984303-b6f65740-5487-4027-a6a8-c1ea46e015c7.png)

**Comment by clin-nick** [comment]
Let me create a new branch to change phot_opt from 3 to 4 and see if it is more stable.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by weiwilliam** [comment]
I can give it a try and run it on the reserved nodes.
Besides phot_opt, any other options should I change?

**Comment by clin-nick** [comment]
No. only need to set phot_opt=4
I linked the needed files to /network/rit/lab/lulab/share_lib/WRF/WRF_TEST/WRF_O3_traceback/run/.
It should be ok to run WRF-Chem with phot_opt=4.
________________________________

**Comment by weiwilliam** [comment]
Okay, it's running, let's see if it can run beyond 38 hours.

**Comment by weiwilliam** [comment]
@clin-nick @SarahLu-NOAA 
Good news, WRFChem can successfully finish 54 hours forecast with phot_opt = 4.
It took about 5 hours to finish.
Before I start the routine run, do we want to test a larger timestep?

**Comment by clin-nick** [comment]
Maybe we could try 15 -> 20 seconds.
________________________________

**Comment by weiwilliam** [comment]
@clin-nick Yeah, let's see the differences.
I'll keep the wrfout and run a new one with 20 seconds, then we can have some quick comparisons.

**Comment by weiwilliam** [comment]
With 20 seconds, finished without problem. 4 hour 15 minutes is needed for 54 hours.

**Comment by weiwilliam** [comment]
@clin-nick @SarahLu-NOAA 
Timestep 15 sec (left) vs 20 sec (right)
Ozone 54 hours forecast
![spa_O3_2023-04-20_06Z_NYS_15vs20](https://user-images.githubusercontent.com/10061966/235735510-14771aa7-782c-4e27-969b-94ca884bbb86.png)
PM2.5 54 hours forecast
![spa_PM25_2023-04-20_06Z_NYS_15vs20](https://user-images.githubusercontent.com/10061966/235735543-3454e9d2-b3a3-4185-989f-e68a606b87b8.png)
Almost no differences.
With 20 seconds timestep, it needs about 4.5 hours to finish.
I think we can use 20 seconds.

**Comment by weiwilliam** [comment]
@clin-nick @SarahLu-NOAA 
I'm testing the new schedule with 20s timestep and phot_opt=4.
01, 02, 03:30 UTC to run prior day 06,12,18 cycles.
04:30 UTC will start the 00z cycle.
The Eastern Time is 21, 22, 23, 00 30 EDT.
If everything goes as scheduled, the 00z cycle should be available before 6:30 EDT.

**Comment by SarahLu-NOAA** [comment]
@weiwilliam @clin-nick 
Very minor differences between the two runs.
Once the config (time step, phot_opt) and workflow is finalized, please update the flow chart (will sent by email)

**Comment by weiwilliam** [comment]
@clin-nick @SarahLu-NOAA 
The updated schedule is
01:30 UTC: submit the run for 06Z-18Z of the prior day (PDY-1)
04:30 UTC: submit the 00Z cycle for 54 hours forecasts.
The first attempt was good, there was about 15 minutes buffer zone before 00Z submission.
